server:
  port: "22123"

spring:
  datasource:
    driver-class-name: "oracle.jdbc.OracleDriver"
    url: "jdbc:oracle:thin:@192.168.0.63:1521:XE"
    username: "ILBO_SNS_DB"
    password: "1111"
    
